nodes:
- input.visual:
    # source: /home/frank/git-repo/aiap/PeekingDuck/data/images/image3.jpg
    source: 0
# - model.yolov6 # this will not work, as the models are imported from the installed package
- custom_nodes.model.yolov6_node # use the custom node
- draw.bbox:
    show_labels: True
- custom_nodes.draw.score
- output.screen
